### PR TITLE
ci: promote to upbound marketplace

### PR DESCRIPTION
**Pull request by Duologic**
Fixes the CI job to promote this provider to the marketplace.

### CODE REVIEW

**Review by iainlane — COMMENTED** [review]
I don't really understand how this works right now --- there's this

https://github.com/crossplane-contrib/provider-sql/blob/61a16726f9782ddfa117045e87adfa8937e318c0/Makefile#L54-L56

Just wondering if that matters, mainly being new to this pipeline and not knowing anything about publishing to the marketplace. 🙃

**Comment by Duologic** [comment]
cc/ @hasheddan Can you enlighten us?

**Comment by jastang** [comment]
> I don't really understand how this works right now --- there's this
> 
> https://github.com/crossplane-contrib/provider-sql/blob/61a16726f9782ddfa117045e87adfa8937e318c0/Makefile#L54-L56
> 
> Just wondering if that matters, mainly being new to this pipeline and not knowing anything about publishing to the marketplace. 🙃

hey there @iainlane -- this isn't required to publish to the Upbound marketplace. this repo is already configured to do so when CI is run on specific branches (see: https://github.com/upbound/build/blob/master/makelib/xpkg.mk#L119-L123)

I see a few tags have already been pushed to the repository: https://explore.ggcr.dev/?repo=xpkg.upbound.io%2Fcrossplane-contrib%2Fprovider-sql. To have these be indexed into a Marketplace listing, they will need to have an explicit release tag, e.g. `v0.7.0`.

**Review by iainlane — APPROVED** [review]

**Comment by danielloader** [comment]
Thanks for the work here - how long do you think it'll take before the marketplace lists this provider?

**Comment by fgaillot-qosenergy** [comment]
Hello,

I would like to test the new v0.9.0 version but image is not available on the Upbound marketplace. Would it be possible to publish this image ? I guess it would also make the marketplace lists this provider on their UI.

Thanks

**Comment by haarchri** [comment]
@fgaillot-qosenergy it's now available via: xpkg.upbound.io/crossplane-contrib/provider-sql:v0.9.0 - started the public listing in Upbound Marketplace - will be happen latest next week

**Comment by haarchri** [comment]
marketplace listing is done https://marketplace.upbound.io/providers/crossplane-contrib/provider-sql/v0.9.0

**Pull request merged**
