### PR TITLE
fix(integration): update mariaDB chart

### PR DESCRIPTION
**Pull request by Duologic**
### Description of your changes

The current chart does not seem to exist anymore (as reported in #97, this should fix
that.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

Run e2e test

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by Duologic** [comment]
cc/ @augustomelo

**Comment by augustomelo** [comment]
Once this is merged on master I will merge it on my branch

**Comment by cskinfill** [comment]
any updates?

**Review by haarchri — APPROVED** [review]
LGTM

**Review by chlunde — APPROVED** [review]

**Review by muvaf — APPROVED** [review]
Thank you!

**Review by turkenh — APPROVED** [review]

**Review by negz — APPROVED** [review]

**Pull request merged**
