### PR TITLE
Fixed database by passing a default value

### LINKED ISSUE #79: GRANTs Failing for Several Grant Types
### What happened?
I'm attempting to create several GRANTs in MySQL. A few succeed, but several fail with `cannot create grant: Error 1221: Incorrect usage of DB GRANT and GLOBAL PRIVILEGES`. It seems to be related to the specific GRANT types I am trying to create.

`PROCESS, REPLICATION CLIENT, REPLICATION SLAVE` in particular.

I can create the failing GRANTs from the MySQL CLI without any issue, using the same username/password that Crossplane is using.

Other GRANT objects with different sets of GRANT types work correctly and create the grants. e.g. `"SELECT","INSERT","UPDATE",
"DELETE","EXECUTE","CREATE TEMPORARY TABLES"`

```
NAME                                              READY   SYNCED   AGE    ROLE                DATABASE               PRIVILEGES
grant.mysql.sql.crossplane.io/datadog-perf        True    True     2d6h   datadog             performance_schema.*   ["SELECT"]
grant.mysql.sql.crossplane.io/datadog-repl        False   False    2d6h   datadog             *.*                    ["REPLICATION CLIENT","PROCE
SS"]
grant.mysql.sql.crossplane.io/somegrantfoo     True    True     2d7h   someuser     *.*                    ["SELECT","INSERT","UPDATE",
"DELETE","EXECUTE","CREATE TEMPORARY TABLES"]
```

### How can we reproduce it?
``` yaml
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: datadog-repl
spec:
  providerConfigRef:
    name: foo
  forProvider:
    privileges:
      - REPLICATION CLIENT
      - PROCESS
    userRef:
      name: datadog
    database: "*.*"
```

### What environment did it happen in?
Crossplane version:  

`Image:         crossplane/crossplane:v1.7.0`
`Image:         crossplane/provider-sql-controller:v0.4.1`

* Cloud: Azure MySQL Flexible Server v8.0
* Kubernetes version:
``` sh
> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"5963a7a5570a1b8c977c31ced503cb20f0ef6e8c", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:42Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution: Azure AKS
* OS (e.g. from /etc/os-release)
``` sh
> # cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
```
* Kernel (e.g. `uname -a`)
``` sh 
 uname -a
Linux aks-lab90-23705758-vmss000001 5.4.0-1069-azure #72~18.04.1-Ubuntu SMP Mon Feb 7 11:12:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Debug Log
```
provider-sql 2022-04-04T03:21:03.853Z	DEBUG	provider-sql	Cannot create external resource	{"controller": "managed/grant.mysql.sql.crossplane.io", "request": "/datadog-repl", "uid": "1a84a73b-e5d0-4958-92b1-07d82e0992b1", "version": "185563119", "external-name": "datadog-repl", "error": "cannot create grant: Error 1221: Incorrect usage of DB GRANT and GLOBAL PRIVILEGES", "errorVerbose": "Error 1221: Incorrect usage of DB GRANT and GLOBAL PRIVILEGES\ncannot create grant\ngithub.com/crossplane-contrib/provider-sql/pkg/controller/mysql/grant.(*external).Create\n\t/home/runner/work/provider-sql/provider-sql/pkg/controller/mysql/grant/reconciler.go:249\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/github.com/crossplane/crossplane-runtime@v0.13.0/pkg/reconciler/managed/reconciler.go:670\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:293\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:248\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/work/provider-sql/provider-sql/.work/pkg/pkg/mod/k8s.io/apimachinery@v0.20.1/pkg/util/wait/wait.go:99\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581"}
```

### PR DESCRIPTION
**Pull request by augustomelo**
### Description of your changes
Since the docs says the database is optional, I made it in the code to option, because actually if you don't pass a value this following error occurs:
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
...
/home/runner/work/provider-sql/provider-sql/pkg/controller/mysql/grant/reconciler.go:143 +0x98
```
This also will fix #79 and #84 
Also the documentation was updated to reflect that

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
I am not a go guys but when running the `make reviewable` I got this error:
```
Can't run linter unused: buildir: failed to load package goarch: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool
ERRO Running error: buildir: failed to load package goarch: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool
```
I installed go1.17.11 as is stated in the docs and go1.13.15 as is stated in `go.mod`

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### Update
1. The problem was that I was just aliasing the go1.17.11 to go and that does not work, you really need to update your PATH variable

### CODE REVIEW

**Review by prshoper — APPROVED** [review]

**Comment by augustomelo** [comment]
@Duologic could you approve it to run the e2e test ?

**Comment by Duologic** [comment]
I would but I don't know how to kick it off :scream: Github!?

**Comment by Duologic** [comment]
Can you perhaps squash the last two commits together to trigger the CI?

**Comment by Duologic** [comment]
I made #104 to run the CI, we can merge that if CI is green, is that okay for you?

**Comment by augustomelo** [comment]
Hey @Duologic thanks for that, I was looking at your PR #104  and it seems that if failed because of the installation of the mariadb
```
 "bitnami" has been added to your repositories
Error: INSTALLATION FAILED: failed to download "bitnami/mariadb" at version "9.0.1"
```

I thought that you needed to [approve](https://docs.github.com/articles/about-pull-request-reviews/) the PR to it be able to run, but it does not seem right, I will squash the commits and force push it, I think you can close #104

**Comment by augustomelo** [comment]
Hey @Duologic  it seems that at least one contributor need to approve the PR to make the workflow run, could you try this: [approving workflow](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

**Comment by Duologic** [comment]
This time I got the "approve and run" button.

**Comment by augustomelo** [comment]
The problem is on this line: https://github.com/crossplane-contrib/provider-sql/blob/ed6c55ce4798967e7652a4cce9f844b99ac1bbb7/cluster/local/integration_tests.sh#L189

This is strange, it seems that this version does not exist anymore:
```
helm search repo bitnami/mariadb --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/mariadb         11.3.0          10.6.9          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.2.2          10.6.9          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.2.1          10.6.9          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.2.0          10.6.9          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.8          10.6.9          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.7          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.6          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.5          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.4          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.3          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.2          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.1          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.1.0          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.14         10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.13         10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.12         10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.11         10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.10         10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.9          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.8          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.7          10.6.8          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.6          10.6.7          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.5          10.6.7          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.4          10.6.7          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.3          10.6.7          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.2          10.6.7          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.1          10.6.7          MariaDB is an open source, community-developed ...
bitnami/mariadb         11.0.0          10.6.7          MariaDB is an open source, community-developed ...
bitnami/mariadb         10.5.1          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.5.0          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.4.6          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.4.5          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.4.4          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.4.2          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.4.1          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.4.0          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.3.7          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.3.6          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.3.5          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.3.4          10.5.15         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.3.3          10.5.13         MariaDB is an open source, community-developed ...
bitnami/mariadb         10.3.2          10.5.13         Fast, reliable, scalable, and easy to use open-...
bitnami/mariadb         10.3.1          10.5.13         Fast, reliable, scalable, and easy to use open-...
bitnami/mariadb         10.3.0          10.5.13         Fast, reliable, scalable, and easy to use open-...
bitnami/mariadb-galera  7.4.1           10.6.9          MariaDB Galera is a multi-primary database clus..
```

We should create a new PR to upgrade it

**Comment by Duologic** [comment]
#105 is merged, can you rebase?

**Comment by augustomelo** [comment]
Hey @Duologic I rebased this commit, could you approve the workflow ?

https://github.com/crossplane-contrib/provider-sql/actions/runs/3515227013

**Review by Duologic — APPROVED** [review]

**Pull request merged**
