### PR TITLE
fix: remove unneeded flush privileges call for mysql #141 

### LINKED ISSUE #141: [mysql] FLUSH PRIVILEGES is only required after making manual edits to tables such as mysql.user, not after CREATE, ALTER or DROP USER
### What problem are you facing?

Why every time a `CREATE`, `ALTER` or `DROP USER` statement is executed, `FLUSH PRIVILEGES` is called after? It's also present after `GRANT` and `REVOKE` statements.

According to mysql documentation executing `FLUSH PRIVILEGES` is only required If you modify the grant tables directly using statements such as [INSERT](https://dev.mysql.com/doc/refman/8.0/en/insert.html), [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html), or [DELETE](https://dev.mysql.com/doc/refman/8.0/en/delete.html) (which is not recommended), the changes have no effect on privilege checking until you either tell the server to reload the tables or restart it. (https://dev.mysql.com/doc/refman/8.0/en/privilege-changes.html). Other references: 
- https://stackoverflow.com/questions/36463966/mysql-when-is-flush-privileges-in-mysql-really-needed
- https://docs.pingcap.com/tidb/dev/sql-statement-flush-privileges

### How could Crossplane help solve your problem?

Remove `FLUSH PRIVILEGES` statements from user and grant controllers, for example:
```go
if err := c.db.Exec(ctx, xsql.Query{
		String: "FLUSH PRIVILEGES",
	}); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errFlushPriv)
	}
```
https://github.com/crossplane-contrib/provider-sql/blob/master/pkg/controller/mysql/user/reconciler.go#L271

I would like to work in a pr if this is considered as desirable

### PR DESCRIPTION
**Pull request by mariusziemke**
### Description of your changes

Fixes #141 

According to mysql documentation executing FLUSH PRIVILEGES is only required If you modify the grant tables directly using statements such as [INSERT](https://dev.mysql.com/doc/refman/8.0/en/insert.html), [UPDATE](https://dev.mysql.com/doc/refman/8.0/en/update.html), or [DELETE](https://dev.mysql.com/doc/refman/8.0/en/delete.html) (which is not recommended), the changes have no effect on privilege checking until you either tell the server to reload the tables or restart it. ([dev.mysql.com/doc/refman/8.0/en/privilege-changes.html](https://dev.mysql.com/doc/refman/8.0/en/privilege-changes.html)). Other references:

[stackoverflow.com/questions/36463966/mysql-when-is-flush-privileges-in-mysql-really-needed](https://stackoverflow.com/questions/36463966/mysql-when-is-flush-privileges-in-mysql-really-needed)
[docs.pingcap.com/tidb/dev/sql-statement-flush-privileges](https://docs.pingcap.com/tidb/dev/sql-statement-flush-privileges)

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

The change has been running in our various dev and production environments for a few weeks now. We tried to break our database clusters by adding and removing lots of users concurrently and everything works as expected. Before removing the Flush Privileges call we had a lot of trouble in our replicated db setup which tried to protect itself from inconsistency by just shutting down after adding more then one user at the same time.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mariusziemke** [comment]
Hi, can anyone look into this PR? Thanks!

**Comment by Jibux** [comment]
We are interested on this fix because we have issue with our percona xtradb cluster witch can be stuck because of `FLUSH PRIVILEGES`. Thanks in advance for the reviewer(s).

**Comment by fgaillot-qosenergy** [comment]
Also interested for having this merged for the next release, thanks in advance.

**Comment by Duologic** [comment]
Would you mind rebasing?

**Comment by mariusziemke** [comment]
@Duologic done.

**Comment by Duologic** [comment]
Ah sorry, missed that this would conflict with #171, this might even simplify it more.

**Comment by Duologic** [comment]
Merged in #202

**Pull request closed without merging**
